apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs-share/mysql
    server: 10.99.1.31
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /var/nfs-share/wordpress
    server: 10.99.1.31
