apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs-mongo0
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.99.1.31
    path: /var/nfs-share/mongo-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs-mongo1
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.99.1.31
    path: /var/nfs-share/mongo-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs-mongo2
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.99.1.31
    path: /var/nfs-share/mongo-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-nfs-mongo3
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.99.1.31
    path: /var/nfs-share/mongo-3
